spring:
  datasource:
    username: root
    password: Tookyosht1!
    url: jdbc:mysql://localhost:3306/onlinemarketplace
    
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    defer-datasource-initialization: true

